defmodule Toolshed.WorkflowsTest do
  @moduledoc """
  The PD-003 storyline as falsifiable tests (Toolshed one-pager §3).

  Each test is one beat of the demo storyline over the real `Lattice.Sim`
  harness — the same substrate Township's W0–W4 run on. The Shed is the
  membership/inventory Replica; each tool is its own `Toolshed.Tool` Replica
  whose dual-signed custody path is pinned by `Toolshed.CustodyConsentTest`
  (ADR 0007). These tests cover the product cut around it: vouch-gated
  admission priced as a TTL'd invite Cap, offline-convergent listings, the
  due-back caveat as a plan-149 lease with overdue *computed*, the Q-06
  return/dispute surface, and steward succession with dump/restore survival.
  """
  use ExUnit.Case, async: true

  alias Lattice.Sim
  alias Toolshed.{Shed, Tool}

  @shed "replica:shed:maple-block"
  @tool "replica:tool:tile-saw"

  defp maple_block(realms) do
    Sim.new(Shed, @shed, realms, seed: "toolshed")
  end

  defp tile_saw(realms) do
    Sim.new(Tool, @tool, realms, seed: "toolshed")
  end

  # ------------------------------------------------------------------ T0
  test "T0 — join by vouch: only a neighbor-issued, unexpired invite Cap admits" do
    sim = maple_block(["founder", "newcomer", "drifter"])

    {sim, _genesis} =
      Sim.create_replica(sim, "founder",
        policies: %{steward: %{successor: "newcomer", dormant_ticks: 3}}
      )

    # The invite: an attenuated (vouch/list only), TTL'd (lease) capability,
    # generated by an existing neighbor — handed over across the fence.
    {sim, invite} =
      Sim.grant(sim, "founder", "newcomer", ops: [:vouch_in, :list_tool], expires_epoch: 2)

    sim = Sim.sync_all(sim)

    {sim, joined} = Sim.command(sim, "newcomer", :vouch_in, ["newcomer"], cap: invite.id)
    sim = Sim.sync_all(sim)

    assert Sim.quarantined(sim, "founder", joined.id) == false

    assert "newcomer" in Sim.state(sim, "founder").neighbors,
           "a vouched-in identity must appear in the converged neighbor set"

    # ASSERT: an identity holding no invite cannot admit itself. The rogue op
    # cites no capability, so every realm quarantines it (:no_capability).
    {sim, rogue} = Sim.command(sim, "drifter", :vouch_in, ["drifter"], cap: :none)
    sim = Sim.sync_all(sim)

    assert {true, :no_capability} = Sim.quarantined(sim, "founder", rogue.id)
    refute "drifter" in Sim.state(sim, "founder").neighbors
    refute "drifter" in Sim.state(sim, "newcomer").neighbors

    # ASSERT: the invite is TTL'd — once the root beacons past its lease, a
    # further admission through it quarantines :lease_expired on every realm.
    {sim, _beacon} = Sim.beacon(sim, "founder", 3)
    sim = Sim.sync_all(sim)

    {sim, late} = Sim.command(sim, "newcomer", :vouch_in, ["late-cousin"], cap: invite.id)
    sim = Sim.sync_all(sim)

    assert {true, :lease_expired} = Sim.quarantined(sim, "founder", late.id)
    assert {true, :lease_expired} = Sim.quarantined(sim, "newcomer", late.id)
    refute "late-cousin" in Sim.state(sim, "founder").neighbors
  end

  # ------------------------------------------------------------------ T1
  test "T1 — shed inventory: an offline-edited listing converges after heal" do
    sim = tile_saw(["owner", "neighbor"])
    {sim, _genesis} = Sim.create_replica(sim, "owner")
    {sim, _} = Sim.grant(sim, "owner", "neighbor", ops: [:describe, :note_condition])
    sim = Sim.sync_all(sim)

    {sim, _} = Sim.command(sim, "owner", :describe, ["Tile saw, 7in wet blade"])
    sim = Sim.sync_all(sim)

    # Partition; both sides keep editing the listing from their own device.
    sim = Sim.partition(sim, "owner", "neighbor")
    {sim, _} = Sim.command(sim, "owner", :describe, ["Tile saw, 7in wet blade, new fence"])
    {sim, _} = Sim.command(sim, "neighbor", :describe, ["Tile saw (blade wobbles a bit)"])
    {sim, _} = Sim.command(sim, "neighbor", :note_condition, ["blade guard cracked, still safe"])

    sim = sim |> Sim.heal("owner", "neighbor") |> Sim.sync_all()

    owner_state = Sim.state(sim, "owner")
    neighbor_state = Sim.state(sim, "neighbor")

    # ASSERT (property a): the listing converges — no coordinator, no host.
    assert owner_state.description == neighbor_state.description
    assert owner_state.condition_notes == neighbor_state.condition_notes

    assert "blade guard cracked, still safe" in owner_state.condition_notes,
           "the offline condition note must land after heal"
  end

  # ------------------------------------------------------------------ T1 property
  test "T1 (property c) — same seed ⇒ byte-identical materialized listing" do
    run = fn ->
      sim = tile_saw(["owner", "neighbor"])
      {sim, _} = Sim.create_replica(sim, "owner")
      {sim, _} = Sim.grant(sim, "owner", "neighbor", ops: [:describe, :note_condition])
      sim = Sim.sync_all(sim)
      sim = Sim.partition(sim, "owner", "neighbor")
      {sim, _} = Sim.command(sim, "owner", :describe, ["A"])
      {sim, _} = Sim.command(sim, "neighbor", :describe, ["B"])
      sim = sim |> Sim.heal("owner", "neighbor") |> Sim.sync_all()
      {Sim.state(sim, "owner"), Lattice.Log.topo_ops(Sim.log(sim, "owner"))}
    end

    assert run.() == run.(),
           "deterministic replay must produce identical listing bytes for identical seed"
  end

  # Owner establishes the tool, the borrower posts a durable custody request
  # (the Q-06 surface), and the dual-signed handoff lands together with the
  # borrow Cap — a lease whose `expires_epoch` IS the due-back caveat.
  # Returns {sim, borrow_cap, transfer_op}.
  defp borrowed_setup(due_epoch) do
    sim = tile_saw(["owner", "borrower"])
    {sim, _genesis} = Sim.create_replica(sim, "owner")
    sim = Sim.sync_all(sim)
    {sim, request} = Sim.request(sim, "borrower", "custody", {:custody_transfer, []})
    sim = Sim.sync_all(sim)

    owner = Sim.identity(sim, "owner")
    borrower = Sim.identity(sim, "borrower")

    consent =
      Lattice.Authority.Consent.sign_custody(borrower, Sim.replica(sim), request.id, owner.pub)

    {sim, transfer} =
      Sim.command(sim, "owner", :custody_transfer, [borrower.pub, request.id, consent])

    {sim, borrow_cap} =
      Sim.grant(sim, "owner", "borrower", ops: [:note_condition], expires_epoch: due_epoch)

    {Sim.sync_all(sim), borrow_cap, transfer}
  end

  # ------------------------------------------------------------------ T2
  test "T2 — due-back caveat: the borrow Cap lease lapses identically on every realm" do
    {sim, borrow_cap, transfer} = borrowed_setup(2)

    assert Sim.quarantined(sim, "owner", transfer.id) == false
    assert Sim.state(sim, "borrower").holder == Sim.identity(sim, "borrower").pub

    # Within the due-back window the borrower's condition note is honored.
    {sim, early} =
      Sim.command(sim, "borrower", :note_condition, ["picked up, blade sharp"],
        cap: borrow_cap.id
      )

    sim = Sim.sync_all(sim)

    # The borrower goes offline; the shed's root beacons past the due-back.
    sim = Sim.partition(sim, "owner", "borrower")
    {sim, _beacon} = Sim.beacon(sim, "owner", 3)

    {sim, late} =
      Sim.command(sim, "borrower", :note_condition, ["returning soon, promise"],
        cap: borrow_cap.id
      )

    sim = sim |> Sim.heal("owner", "borrower") |> Sim.sync_all()

    # ASSERT (property d): every realm reaches identical lease verdicts —
    # overdue is computed from the record, never asserted or nagged.
    assert Sim.quarantined(sim, "owner", early.id) == false
    assert Sim.quarantined(sim, "borrower", early.id) == false
    assert {true, :lease_expired} = Sim.quarantined(sim, "owner", late.id)
    assert {true, :lease_expired} = Sim.quarantined(sim, "borrower", late.id)

    assert Sim.state(sim, "owner") == Sim.state(sim, "borrower")
    assert "picked up, blade sharp" in Sim.state(sim, "owner").condition_notes
    refute "returning soon, promise" in Sim.state(sim, "owner").condition_notes

    # The custody record itself is untouched by the lapse: the tool is still
    # out, unambiguously, with the borrower — that is what overdue MEANS.
    assert Sim.state(sim, "owner").holder == Sim.identity(sim, "borrower").pub
  end

  # ------------------------------------------------------------------ T3
  test "T3 — 'I returned it': the visible request, then the reverse dual-bound op" do
    {sim, _borrow_cap, _transfer} = borrowed_setup(2)

    # The due-back passes with the tool still out — an overdue loan on record.
    {sim, _beacon} = Sim.beacon(sim, "owner", 3)
    sim = Sim.sync_all(sim)

    # The borrower's return request is a durable :inbox op. This is the
    # dispute answer: either the dual-signed return exists in the DAG, or the
    # unresolved (or refused) request sits visible and timestamped.
    {sim, return_req} = Sim.request(sim, "borrower", "custody", {:custody_transfer, [:return]})
    sim = Sim.sync_all(sim)

    analysis = Lattice.Authority.analyze(Tool, Sim.log(sim, "owner"))

    assert Enum.any?(analysis.requests, fn r ->
             r.op == return_req.id and r.ref == "custody"
           end),
           "an unresolved return request must stay visible in the analyzer output"

    # Q-06: the current validated custody holder (the lender) resolves the
    # request — even after the borrow Cap lapsed, so an overdue loan can
    # always be closed by the record. The borrower's signed half of the
    # return is the request op itself, bound in via `request_op_id`.
    owner = Sim.identity(sim, "owner")

    consent =
      Lattice.Authority.Consent.sign_custody(owner, Sim.replica(sim), return_req.id, owner.pub)

    {sim, return_op} =
      Sim.command(sim, "owner", :custody_transfer, [owner.pub, return_req.id, consent])

    sim = Sim.sync_all(sim)

    assert Sim.quarantined(sim, "owner", return_op.id) == false
    assert Sim.quarantined(sim, "borrower", return_op.id) == false
    assert Sim.state(sim, "owner").holder == owner.pub
    assert Sim.state(sim, "borrower").holder == owner.pub
  end

  # ------------------------------------------------------------------ T4
  test "T4 — the founder moves away: stewardship transfers in one op, their stale op quarantines" do
    sim = maple_block(["founder", "keeper"])

    {sim, _genesis} =
      Sim.create_replica(sim, "founder",
        policies: %{steward: %{successor: "keeper", dormant_ticks: 3}}
      )

    sim = Sim.sync_all(sim)

    # The founder performs a steward-only act — honored.
    {sim, notice} = Sim.command(sim, "founder", :post_bulletin, ["work party Saturday"])
    assert Sim.quarantined(sim, "founder", notice.id) == false

    # One op moves the steward Cap; the shed outlives its founder.
    {sim, _} =
      Sim.transfer(sim, "founder", "keeper", :steward, at_tick: 1, ops: [:post_bulletin])

    sim = Sim.sync_all(sim)

    # The ex-steward's later act causally sees the handoff — quarantined
    # :not_holder on every realm, visibly, by the same predicate as revocation.
    {sim, stale} = Sim.command(sim, "founder", :post_bulletin, ["still in charge?"])
    sim = Sim.sync_all(sim)

    assert {true, :not_holder} = Sim.quarantined(sim, "founder", stale.id)
    assert {true, :not_holder} = Sim.quarantined(sim, "keeper", stale.id)
    assert Sim.holder(sim, "keeper", :steward) == Sim.identity(sim, "keeper").pub
    assert Sim.state(sim, "keeper").bulletin == "work party Saturday"
  end

  # ------------------------------------------------------------------ T4 survival
  test "T4 (survival) — dump/restore preserves the inventory, custody record, and open loan" do
    {sim, _borrow_cap, transfer} = borrowed_setup(4)

    # Kill/restore the borrower's device: the whole shed record — listing,
    # custody history, and the open loan — comes back byte-identical.
    path = Path.join(System.tmp_dir!(), "toolshed_#{System.unique_integer([:positive])}.log")
    log = Sim.log(sim, "borrower")
    :ok = Lattice.Log.dump(log, path)
    {:ok, restored} = Lattice.Log.restore(path)
    File.rm(path)

    assert Lattice.Log.op_ids(restored) == Lattice.Log.op_ids(log)
    assert Lattice.state(Tool, restored) == Lattice.state(Tool, log)

    # The open loan is still on record: the dual-signed transfer is honored
    # and the borrower still holds the tool on the restored view.
    analysis = Lattice.Authority.analyze(Tool, restored)
    refute MapSet.member?(analysis.quarantine, transfer.id)
    assert Lattice.state(Tool, restored).holder == Sim.identity(sim, "borrower").pub
  end
end
