import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const product = JSON.parse(read("../lattice-mobile-core/products.json")).products.find(p => p.product === "treehouse");
const a = "src-tauri/gen/android/";
const activity = read(`${a}app/src/main/java/dev/treetop/lattice/treehouse/MainActivity.kt`);
assert(activity.includes('System.loadLibrary("treehouse_tauri_shell")'));
assert(activity.indexOf("Keyring.initializeNdkContext") < activity.indexOf("super.onCreate"));
const manifest = read(`${a}app/src/main/AndroidManifest.xml`);
assert(manifest.includes('android:allowBackup="false"'));
assert.equal((manifest.match(/android.permission.USE_BIOMETRIC/g) ?? []).length, 1);
// Native review requires this permission; eligibility and public activation remain closed.
const gradle = read(`${a}app/build.gradle.kts`);
assert(gradle.includes("namespace = product.appId") && gradle.includes("applicationId = product.appId"));
assert(gradle.includes('buildConfigField("boolean", "WITNESS_ELIGIBILITY_IMPLEMENTED", "false")'));
assert(gradle.includes("dependsOn(verifyTreehouseReleaseIdentity)"));
assert(!gradle.includes('signingConfigs.getByName("debug")'));
assert(!gradle.includes('manifestPlaceholders["usesCleartextTraffic"] = "true"'));
assert(gradle.includes('ndkVersion = "27.1.12297006"'));
const rules = read(`${a}buildSrc/src/main/kotlin/TreehouseProduct.kt`);
assert(rules.includes('single { it["product"] == "treehouse" }'));
assert(rules.includes(product.androidSigningAlias));
assert(rules.includes('env["TREEHOUSE_PILOT_KEY_ALIAS"] != signingAlias'));
assert(rules.includes('env["TREEHOUSE_ANDROID_SIGNING"] != "pilot"'));
const native = read("src-tauri/src/lib.rs");
assert(native.includes("#[cfg_attr(mobile, tauri::mobile_entry_point)]"));
assert(native.includes("android_keyring::configure()"));
assert(!native.includes("treehouse_witness_"));
const store = read("src-tauri/src/android_keyring.rs");
assert(store.includes("crate::key_store::KEY_SERVICE"));
assert(!store.includes("governance-witness"));
console.log("PASS fixed Android product, separate carrier JNI startup, offline debug and fail-closed release wiring; no witness commands");
